// Code generated by mockery v2.35.4. DO NOT EDIT.

package mocks

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	model "github.com/Alphonnse/filmLibriary/internal/model"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

// GenerateJWT provides a mock function with given fields: ctx, user
func (_m *AuthService) GenerateJWT(ctx context.Context, user *model.UserModel) (string, error) {
	ret := _m.Called(ctx, user)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserModel) (string, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserModel) string); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.UserModel) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// JWTAdminAuth provides a mock function with given fields: _a0
func (_m *AuthService) JWTAdminAuth(_a0 func(http.ResponseWriter, *http.Request)) http.HandlerFunc {
	ret := _m.Called(_a0)

	var r0 http.HandlerFunc
	if rf, ok := ret.Get(0).(func(func(http.ResponseWriter, *http.Request)) http.HandlerFunc); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.HandlerFunc)
		}
	}

	return r0
}

// JWTRegularUserAuth provides a mock function with given fields: _a0
func (_m *AuthService) JWTRegularUserAuth(_a0 func(http.ResponseWriter, *http.Request)) http.HandlerFunc {
	ret := _m.Called(_a0)

	var r0 http.HandlerFunc
	if rf, ok := ret.Get(0).(func(func(http.ResponseWriter, *http.Request)) http.HandlerFunc); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.HandlerFunc)
		}
	}

	return r0
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
